services:
    frontend:
        build:
            context: ./frontend/.
            args:
                VITE_API_URL: http://localhost:3001
        ports:
            - "80:80"
        depends_on:
            - backend

    bd:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_secret
            MYSQL_DATABASE: innovatech_ops
        ports:
            - "3306:3306"
        volumes:
            - db_vol:/var/lib/mysql
            - ./bd:/docker-entrypoint-initdb.d

    backend:
        build: ./backend/.
        restart: unless-stopped
        env_file:
            - ./backend/.env.example
        environment:
            DB_HOST: bd
            CORS_ORIGIN: http://localhost
        ports:
            - "3001:3001"
        depends_on:
            - bd

volumes:
    db_vol:
