name: Frontend Deploy

on:
  push:
    branches:
      - deploy
    paths:
      - 'frontend/**'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend Image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
